### ISSUE TITLE
Chromedriver 127.0.6533.88 issue 

### ISSUE THREAD

**Issue by zuzell** [GoogleChromeLabs/chrome-for-testing#145]
I have a chromedriver version 127.0.6533.88, and chrome version 127.0.6533.89. I am getting below error:

```
DevTools listening on ws://127.0.0.1:9222/devtools/browser/1d64f356-3655-495b-b5f4-4743c5986a46
Message: session not created: This version of ChromeDriver only supports Chrome version 125
Current browser version is 127.0.6533.89 with binary path C:\Program Files\Google\Chrome\Application\chrome.
```

Is 127.0.6533.88 chromedriver compatible with chrome 127.0.6533.89 version? Will there be 127.0.6533.89 distribution of chromedriver?

**Comment by mathiasbynens** [comment]
Looks like the `-win64` archives are missing for 127.0.6533.89:

```
$ npm run check 127.0.6533.89

> check
> node --no-warnings check-version.mjs "127.0.6533.89"

Checking downloads for v127.0.6533.89…
https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.89/linux64/chrome-linux64.zip 200
https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.89/mac-arm64/chrome-mac-arm64.zip 200
https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.89/mac-x64/chrome-mac-x64.zip 200
https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.89/win32/chrome-win32.zip 200
https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.89/win64/chrome-win64.zip 404
https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.89/linux64/chromedriver-linux64.zip 200
https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.89/mac-arm64/chromedriver-mac-arm64.zip 200
https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.89/mac-x64/chromedriver-mac-x64.zip 200
https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.89/win32/chromedriver-win32.zip 200
https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.89/win64/chromedriver-win64.zip 404
https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.89/linux64/chrome-headless-shell-linux64.zip 200
https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.89/mac-arm64/chrome-headless-shell-mac-arm64.zip 200
https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.89/mac-x64/chrome-headless-shell-mac-x64.zip 200
https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.89/win32/chrome-headless-shell-win32.zip 200
https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.89/win64/chrome-headless-shell-win64.zip 404
https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.89/mojojs.zip 200
❌ NOT OK
```

The build failed: https://ci.chromium.org/ui/p/chrome/builders/official.cft/win64-cft/2776/infra

```
[11891/73770] 1m44.02s F ACTION //content/shell:protocol_sources(//build/toolchain/win:win_clang_x64)
FAILED: 7a865850-7189-49d6-8488-f79421fbb037 "./gen/chrome/browser/resources/settings/preprocessed/a11y_page/a11y_page.html.ts" ACTION //chrome/browser/resources/settings:html_wrapper_files(//build/toolchain/win:win_clang_x64)
stderr:
Traceback (most recent call last):
  File "../../tools/polymer/html_to_wrapper.py", line 286, in <module>
    main(sys.argv[1:])
  File "../../tools/polymer/html_to_wrapper.py", line 280, in main
    shutil.rmtree(tmp_out_dir)
  File "C:\b\s\w\ir\cipd_bin_packages\cpython3\bin\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\b\s\w\ir\cipd_bin_packages\cpython3\bin\lib\shutil.py", line 613, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\b\s\w\ir\cipd_bin_packages\cpython3\bin\lib\shutil.py", line 613, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\b\s\w\ir\cipd_bin_packages\cpython3\bin\lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\b\s\w\ir\cipd_bin_packages\cpython3\bin\lib\shutil.py", line 620, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\b\\s\\w\\ir\\cache\\builder\\src\\out\\Release_x64\\gen\\chrome\\browser\\resources\\settings\\preprocessed\\tmp8r7nu2xa\\privacy_page\\privacy_guide'
```

**Comment by mathiasbynens** [comment]
The retry failed again:

```
[10339/73770] 1m27.44s S STAMP obj/chrome/browser/resources/key_value_pair_viewer_shared/html_wrapper_files.stamp
FAILED: c57f6e8a-2f75-4e2f-87c1-8dafa25fb3e8 "./gen/chrome/browser/resources/new_tab_page/preprocessed/app.html.ts" ACTION //chrome/browser/resources/new_tab_page:html_wrapper_files(//build/toolchain/win:win_clang_x64)
stderr:
Traceback (most recent call last):
  File "../../tools/polymer/html_to_wrapper.py", line 286, in <module>
    main(sys.argv[1:])
  File "../../tools/polymer/html_to_wrapper.py", line 280, in main
    shutil.rmtree(tmp_out_dir)
  File "C:\b\s\w\ir\cipd_bin_packages\cpython3\bin\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\b\s\w\ir\cipd_bin_packages\cpython3\bin\lib\shutil.py", line 613, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\b\s\w\ir\cipd_bin_packages\cpython3\bin\lib\shutil.py", line 613, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\b\s\w\ir\cipd_bin_packages\cpython3\bin\lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\b\s\w\ir\cipd_bin_packages\cpython3\bin\lib\shutil.py", line 620, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\b\\s\\w\\ir\\cache\\builder\\src\\out\\Release_x64\\gen\\chrome\\browser\\resources\\new_tab_page\\preprocessed\\tmpuv3zb0vs\\modules\\history_clusters'
```

**Comment by mathiasbynens** [comment]
To answer your question:

> Is 127.0.6533.88 chromedriver compatible with chrome 127.0.6533.89 version?

Yes. https://developer.chrome.com/docs/chromedriver/downloads/version-selection

It’s unfortunate that CfT 127.0.6533.89 is not available but it shouldn’t be a problem for your use case.
