### ISSUE TITLE
Chrome Instance with 127.0.6533.119 abruptly stop with a connection reset warning

### ISSUE THREAD

**Issue by rex3992** [GoogleChromeLabs/chrome-for-testing#159]
Hi,
While running automation on 127.0.6533.119 version, starting last Saturday, the automation builds were not waiting for the defiend timeouts, due to this the browser instance would get close automatically, and the execution would fail.
At first I thought it was something to do with version so I tried with 129.0 and got same failure, however moving back to bonigarcia didn't have same issue. i.e. Normal browser doesnt have this issue, the Chrome for Testing does.

Also, is there a way I can test this with a specific minor version, lets say 127.0.6533.72 or something?

`org.openqa.selenium.WebDriverException: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=127.0.6533.119)
Build info: version: '4.23.1', revision: '656257d8e9'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.11'
Driver info: co.nvqa.common.ui.driver.NvChromeDriver
Command: [faac82b186479218b0079ce362eb0570, getAlertText {}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 127.0.6533.119, chrome: {chromedriverVersion: 127.0.6533.119 (bdef6783a05..., userDataDir: C:\Users\rosha\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:54346}, networkConnectionEnabled: false, pageLoadStrategy: none, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:54346/devtoo..., se:cdpVersion: 127.0.6533.119, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: faac82b186479218b0079ce362eb0570
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:618)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:622)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.alert(RemoteWebDriver.java:1190)
	at co.nvqa.common.ui.support.CommonUiTestUtils.acceptAlertDialogIfAppear(CommonUiTestUtils.java:31)
	at co.nvqa.common.ui.cucumber.glue.selenium.StandardCommonSeleniumSteps.teardown(StandardCommonSeleniumSteps.java:134)`

**Comment by HeavyPunk** [comment]
The same problem

**Comment by Med-d** [comment]
Got same issue on 122.0 and 123.0 major versions

**Comment by mathiasbynens** [comment]
> [!IMPORTANT]
**This issue tracker tracks bugs with [the Chrome for Testing availability dashboard](https://googlechromelabs.github.io/chrome-for-testing/) and [its API](https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints).**
> 
> - Are you reporting a bug that reproduces in Chrome for Testing but not in Chrome? File it here: https://goo.gle/cftbug
> - Are you reporting a bug in Chrome? File it here: https://crbug.com/new

**Comment by mathiasbynens** [comment]
> Raised the issue again here: https://issues.chromium.org/issues/376183216

Thank you!
