### ISSUE TITLE
Missing `chromedriver` for Stable channel

### ISSUE THREAD

**Issue by tcannonfodder** [GoogleChromeLabs/chrome-for-testing#22]
Looking at the availability dashboard: https://googlechromelabs.github.io/chrome-for-testing/ , there are no `chromedriver` binaries for the Stable channel

Likewise, running The puppeteer install command returns the following error:

```
$ npx @puppeteer/browsers install chromedriver       
@puppeteer/browsers install <browser>

Download and install the specified browser. If successful, the command outputs the actual browser buildId that was
installed and the absolute path to the browser executable (format: <browser>@<buildID> <path>).

Positionals:
  browser  Which browser to install <browser>[@<buildId|latest>]. `latest` will try to find the latest available build.
           `buildId` is a browser-specific identifier such as a version or a revision.               [string] [required]

Options:
  --version   Show version number                                                                              [boolean]
  --help      Show help                                                                                        [boolean]
  --platform  Platform that the binary needs to be compatible with.
                                [string] [choices: "linux", "mac", "mac_arm", "win32", "win64"] [default: Auto-detected]
  --path      Path to the root folder for the browser downloads and installation. The installation folder structure is
              compatible with the cache structure used by Puppeteer.       [string] [default: Current working directory]
  --base-url  Base URL to download from                                                                         [string]

Examples:
  @puppeteer/browsers install chrome                            Install the latest available build of the Chrome
                                                                browser.
  @puppeteer/browsers install chrome@latest                     Install the latest available build for the Chrome
                                                                browser.
  @puppeteer/browsers install chromium@1083080                  Install the revision 1083080 of the Chromium browser.
  @puppeteer/browsers install firefox                           Install the latest available build of the Firefox
                                                                browser.
  @puppeteer/browsers install firefox --platform mac            Install the latest Mac (Intel) build of the Firefox
                                                                browser.
  @puppeteer/browsers install firefox --path                    Install to the specified cache directory.
  /tmp/my-browser-cache

Error: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/chromedriver/mac-arm64/chromedriver-mac-arm64.zip
    at /Users/tcannon/.npm/_npx/c99440fc2d0a3f00/node_modules/@puppeteer/browsers/lib/cjs/httpUtil.js:100:31
    at ClientRequest.requestCallback (/Users/blah/.npm/_npx/c99440fc2d0a3f00/node_modules/@puppeteer/browsers/lib/cjs/httpUtil.js:77:13)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:701:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:542:22)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
```

**Comment by mathiasbynens** [comment]
Indeed. From [the README](https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints):

> `chromedriver` (supported since v115.0.5763.0)

More info in the ChromeDriver announcement: https://groups.google.com/g/chromedriver-users/c/clpipqvOGjE/m/5NxzS_SRAgAJ

The `*-with-downloads` JSON API endpoints enumerate the available versions/downloads, including `chromedriver` for versions where it’s available.

**Comment by tcannonfodder** [comment]
Ahhh, gotcha; Thanks Mathias!

I got so excited to try it out that I didn't notice the M115 note 😅
